export const WORK_ITEMS_URL = "_apis/wit/workItems"
export const WORK_ITEMS_BATCH_URL = "_apis/wit/workItemsBatch"
export const TAGS_URL = "_apis/wit/tags"
export const WIT_BATCH_URL = "_apis/wit/$batch"
export const PROJECTS_URL = "_apis/projects"
export const PULL_REQUESTS_URL = "_apis/git/pullrequests"
export const API_VERSION = "7.1"
